# Generated by Django 4.1.5 on 2023-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='coluna',
            field=models.CharField(choices=[('coluna1', 'Coluna 1'), ('coluna2', 'Coluna 2')], default='coluna1', max_length=7, verbose_name='Coluna'),
        ),
    ]
